# Inspired by https://searchfox.org/firefox-main/source/toolkit/components/normandy/components.conf

Classes = [
  {
    'cid': '{4c85223f-3c1b-475a-8527-dc8ef69ca822}',
    'contract_ids': ['@mozilla.org/network/protocol/about;1?what=attribution'],
    'esModule': 'moz-src:///ironfox/about/IronFoxAboutPages.sys.mjs',
    'constructor': 'AboutAttribution',
  },
  {
    'cid': '{a88bc9f2-3cad-4cbd-b97d-3036db4740ff}',
    'contract_ids': ['@mozilla.org/network/protocol/about;1?what=ironfox'],
    'esModule': 'moz-src:///ironfox/about/IronFoxAboutPages.sys.mjs',
    'constructor': 'AboutIronFox',
  },
  {
    'cid': '{9a09220e-2b89-464b-8441-6ca521be9939}',
    'contract_ids': ['@mozilla.org/network/protocol/about;1?what=librewolf'],
    'esModule': 'moz-src:///ironfox/about/IronFoxAboutPages.sys.mjs',
    'constructor': 'AboutLibreWolf',
  },
  {
    'cid': '{b3ac3a21-fb4b-4013-9bcb-bbb4ae1ea861}',
    'contract_ids': ['@mozilla.org/network/protocol/about;1?what=policies'],
    'esModule': 'moz-src:///ironfox/about/IronFoxAboutPages.sys.mjs',
    'constructor': 'AboutPolicies',
  },
  {
    'cid': '{057bb874-aabf-4b9a-a43e-3440c3e4bfa2}',
    'contract_ids': ['@mozilla.org/network/protocol/about;1?what=robots'],
    'esModule': 'moz-src:///ironfox/about/IronFoxAboutPages.sys.mjs',
    'constructor': 'AboutRobots',
  },
]
